import json
from io import BytesIO

import requests
import streamlit as st
from reportlab.pdfgen import canvas


# =====================================================
# CONFIG
# =====================================================

API_URL = "http://127.0.0.1:8000"

st.set_page_config(
    page_title="AI SDLC Review Assistant",
    page_icon="🤖",
    layout="wide"
)


# =====================================================
# SESSION STATE
# =====================================================

if "history" not in st.session_state:
    st.session_state.history = []


# =====================================================
# HELPER FUNCTIONS
# =====================================================

def show_agent_badge(agent):

    if "Architecture" in agent:
        st.success(f"🏗 Detected Agent: {agent}")

    elif "Backend" in agent:
        st.info(f"⚙ Detected Agent: {agent}")

    elif "Frontend" in agent:
        st.info(f"🎨 Detected Agent: {agent}")

    elif "Code" in agent:
        st.warning(f"🔍 Detected Agent: {agent}")

    elif "Testing" in agent:
        st.success(f"🧪 Detected Agent: {agent}")

    else:
        st.info(f"🤖 {agent}")


def generate_pdf(data):

    buffer = BytesIO()

    pdf = canvas.Canvas(buffer)

    pdf.setTitle("AI SDLC Review Report")

    pdf.setFont(
        "Helvetica-Bold",
        18
    )

    pdf.drawString(
        50,
        800,
        "AI SDLC REVIEW REPORT"
    )

    pdf.setFont(
        "Helvetica",
        12
    )

    pdf.drawString(
        50,
        780,
        "Generated by AI SDLC Review Assistant"
    )

    pdf.drawString(
        50,
        750,
        f"Review Type: {data.get('reviewType', '')}"
    )

    pdf.drawString(
        50,
        730,
        f"Agent: {data.get('agent', '')}"
    )

    pdf.line(
        50,
        715,
        550,
        715
    )

    response_text = str(
        data.get(
            "response",
            ""
        )
    )

    y = 690

    for line in response_text.split("\n"):

        if not line.strip():
            y -= 10
            continue

        pdf.drawString(
            50,
            y,
            line[:120]
        )

        y -= 15

        if y <= 40:

            pdf.showPage()

            y = 800

    pdf.save()

    buffer.seek(0)

    return buffer


def show_summary_cards(data):

    col1, col2, col3 = st.columns(3)

    with col1:

        st.metric(
            "Review Type",
            data.get(
                "reviewType",
                "N/A"
            )
        )

    with col2:

        agent = data.get(
            "agent",
            "Unknown"
        )

        st.metric(
            "Detected Agent",
            agent
        )

    with col3:

        response_size = len(
            str(
                data.get(
                    "response",
                    ""
                )
            )
        )

        st.metric(
            "Response Size",
            response_size
        )


def display_result(data):

    st.success(
        "✅ Review Completed"
    )

    show_summary_cards(data)

    st.markdown("---")

    show_agent_badge(
        data.get(
            "agent",
            "Unknown"
        )
    )

    st.subheader(
        "📋 Detailed Review"
    )

    with st.expander(
        "View Full Review",
        expanded=True
    ):

        st.markdown(
            data.get(
                "response",
                "No response available."
            )
        )

    st.markdown("---")

    col1, col2 = st.columns(2)

    with col1:

        st.download_button(
            label="📥 Download JSON Report",
            data=json.dumps(
                data,
                indent=2
            ),
            file_name="review_report.json",
            mime="application/json",
            use_container_width=True
        )

    with col2:

        pdf_file = generate_pdf(
            data
        )

        st.download_button(
            label="📄 Download PDF Report",
            data=pdf_file,
            file_name="review_report.pdf",
            mime="application/pdf",
            use_container_width=True
        )


# =====================================================
# HEADER
# =====================================================

st.title(
    "🤖 AI SDLC Review Assistant"
)

st.success(
    """
    Single AI Chatbot for:

    🏗 Architecture Review

    ⚙ Backend Review

    🎨 Frontend Review

    🔍 Code Review

    🧪 Testing Review
    """
)

st.markdown(
    """
### Features

✅ Requirements & Architecture Review

✅ Backend API Review

✅ Frontend Review

✅ Code Review

✅ Testing Review

✅ File Upload Based Review

✅ PDF Report Export

✅ Review History

✅ Agent Analytics

✅ Executive Dashboard
"""
)

st.divider()


# =====================================================
# TABS
# =====================================================

tab1, tab2 = st.tabs(
    [
        "💬 Ask Question",
        "📂 Upload File"
    ]
)


# =====================================================
# TAB 1 : ASK QUESTION
# =====================================================

with tab1:

    st.subheader(
        "Ask Anything"
    )

    query = st.text_area(
        "Enter your question",
        height=150,
        placeholder="Example: Design a microservices based ecommerce architecture"
    )

    if st.button(
        "Review Query",
        use_container_width=True
    ):

        if not query.strip():

            st.warning(
                "Please enter a question."
            )

        else:

            try:

                with st.spinner(
                    "Reviewing..."
                ):

                    response = requests.post(
                        f"{API_URL}/review",
                        json={
                            "query": query
                        },
                        timeout=300
                    )

                    data = response.json()

                st.session_state.history.append(
                    {
                        "type": "question",
                        "query": query,
                        "agent": data.get(
                            "agent"
                        ),
                        "reviewType": data.get(
                            "reviewType"
                        )
                    }
                )

                display_result(
                    data
                )

            except Exception as ex:

                st.error(
                    f"Error: {str(ex)}"
                )


# =====================================================
# TAB 2 : FILE REVIEW
# =====================================================

# =====================================================
# TAB 2 : MULTI FILE REVIEW
# =====================================================

with tab2:

    st.subheader(
        "Upload and Review Multiple Files"
    )

    uploaded_files = st.file_uploader(
        "Choose Files",
        accept_multiple_files=True,
        type=[
            "pdf",
            "txt",
            "java",
            "py",
            "yaml",
            "yml",
            "json",
            "js",
            "jsx",
            "ts",
            "tsx"
        ]
    )

    if uploaded_files:

        st.success(
            f"{len(uploaded_files)} file(s) selected"
        )

        st.markdown("### Selected Files")

        for file in uploaded_files:

            st.write(
                f"📄 {file.name}"
            )

        if st.button(
            "🚀 Review All Files",
            use_container_width=True
        ):

            try:

                files_payload = []

                for file in uploaded_files:

                    files_payload.append(
                        (
                            "files",
                            (
                                file.name,
                                file,
                                file.type
                            )
                        )
                    )

                with st.spinner(
                    "Analyzing Multiple Files..."
                ):

                    response = requests.post(
                        f"{API_URL}/review-multiple-files",
                        files=files_payload,
                        timeout=600
                    )

                    data = response.json()

                summary = data.get(
                    "executiveSummary",
                    {}
                )

                st.success(
                    "✅ Multi File Review Completed"
                )

                st.subheader(
                    "📊 Executive Summary"
                )

                col1, col2, col3 = st.columns(3)

                with col1:

                    st.metric(
                        "Total Files",
                        summary.get(
                            "totalFiles",
                            0
                        )
                    )

                with col2:

                    st.metric(
                        "Architecture Reviews",
                        summary.get(
                            "architectureReviews",
                            0
                        )
                    )

                with col3:

                    st.metric(
                        "Backend Reviews",
                        summary.get(
                            "backendReviews",
                            0
                        )
                    )

                col4, col5, col6 = st.columns(3)

                with col4:

                    st.metric(
                        "Frontend Reviews",
                        summary.get(
                            "frontendReviews",
                            0
                        )
                    )

                with col5:

                    st.metric(
                        "Code Reviews",
                        summary.get(
                            "codeReviews",
                            0
                        )
                    )

                with col6:

                    st.metric(
                        "Testing Reviews",
                        summary.get(
                            "testingReviews",
                            0
                        )
                    )

                st.markdown("---")

                st.subheader(
                    "📋 Individual File Reviews"
                )

                reviews = data.get(
                    "reviews",
                    []
                )

                for review_item in reviews:

                    file_name = review_item.get(
                        "fileName",
                        "Unknown"
                    )

                    review_data = review_item.get(
                        "review",
                        {}
                    )

                    agent = review_data.get(
                        "agent",
                        "Unknown"
                    )

                    with st.expander(
                        f"📄 {file_name}",
                        expanded=False
                    ):

                        show_agent_badge(
                            agent
                        )

                        st.markdown(
                            review_data.get(
                                "response",
                                "No response available."
                            )
                        )

                        st.session_state.history.append(
                            {
                                "type": "file",
                                "file": file_name,
                                "agent": agent,
                                "reviewType": review_data.get(
                                    "reviewType",
                                    "Unknown"
                                )
                            }
                        )

                st.download_button(
                    label="📥 Download Combined JSON Report",
                    data=json.dumps(
                        data,
                        indent=2
                    ),
                    file_name="combined_review_report.json",
                    mime="application/json",
                    use_container_width=True
                )

            except Exception as ex:

                st.error(
                    f"Error: {str(ex)}"
                )